spring:
  # DataBase
  dataSource:
    url: jdbc:mysql://db:3306/db
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
